language: python

python:
  - "3.7"

install:
  - pip install pylint  # flake8

script:
- pylint -E .\classify_document.py
# - flake8 --max-line-length=120  # still broken for python 3.7 (13/9/18)

branches:
  only:
    - master
